"""Add photo_url default state in AbstractBaseUserModel for the S3 integration

Revision ID: 14f406eeabf9
Revises: e2dfb516e97b
Create Date: 2022-08-29 23:12:00.745798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14f406eeabf9"
down_revision = "e2dfb516e97b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admin_user", "photo_url", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "moderator_user",
        "photo_url",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "regular_user",
        "photo_url",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "regular_user", "photo_url", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "moderator_user",
        "photo_url",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "admin_user", "photo_url", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
