"""WorkouModel 1:many relationship with RegularUser, ExerciseModel 1:many relationship with WorkoutModel

Revision ID: 74f4024410ae
Revises: b151b898673e
Create Date: 2022-08-28 23:46:28.490033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f4024410ae'
down_revision = 'b151b898673e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_model', sa.Column('workout_pk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exercise_model', 'workout_model', ['workout_pk'], ['id'])
    op.add_column('workout_model', sa.Column('users_pk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workout_model', 'regular_user', ['users_pk'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_model', type_='foreignkey')
    op.drop_column('workout_model', 'users_pk')
    op.drop_constraint(None, 'exercise_model', type_='foreignkey')
    op.drop_column('exercise_model', 'workout_pk')
    # ### end Alembic commands ###
