"""Added ON Delete - Cascade on ExerciseModel

Revision ID: 93b7cda173ef
Revises: 95717338a062
Create Date: 2022-08-29 01:51:11.491359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b7cda173ef'
down_revision = '95717338a062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercise_model_workout_pk_fkey', 'exercise_model', type_='foreignkey')
    op.create_foreign_key(None, 'exercise_model', 'workout_model', ['workout_pk'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_model', type_='foreignkey')
    op.create_foreign_key('exercise_model_workout_pk_fkey', 'exercise_model', 'workout_model', ['workout_pk'], ['id'])
    # ### end Alembic commands ###
