"""Changed ForeignKey to moderator_user.pk on VideoModel - FIX

Revision ID: 95717338a062
Revises: 74f4024410ae
Create Date: 2022-08-29 01:28:41.868019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95717338a062'
down_revision = '74f4024410ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('video_model_users_pk_fkey', 'video_model', type_='foreignkey')
    op.create_foreign_key(None, 'video_model', 'moderator_user', ['users_pk'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_model', type_='foreignkey')
    op.create_foreign_key('video_model_users_pk_fkey', 'video_model', 'regular_user', ['users_pk'], ['pk'])
    # ### end Alembic commands ###
