"""Foreign key between VideoModel and RegularUser added-Test

Revision ID: b151b898673e
Revises: 066689b138c7
Create Date: 2022-08-28 01:08:00.945273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b151b898673e'
down_revision = '066689b138c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_model', sa.Column('users_pk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'video_model', 'regular_user', ['users_pk'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_model', type_='foreignkey')
    op.drop_column('video_model', 'users_pk')
    # ### end Alembic commands ###
